### PR TITLE
Choose Voting Method page done. Part of user story #15. Be wary of me…

### PR DESCRIPTION
**Pull request by Golemwardox**
…rge errors! I think it should combine fine.

### CODE REVIEW

**Comment by Golemwardox** [comment]
Screen Shot 2021-11-01 at 11 26 17 PM

**Review by psc358 — COMMENTED** [review]
Looks good! Could you also remind me what each of the filler texts is going to be replaced with eventually? Maybe we should add an argument so it can be filled in by the actual text once we have the apis.

**Comment by Golemwardox** [comment]
> Looks good! Could you also remind me what each of the filler texts is going to be replaced with eventually? Maybe we should add an argument so it can be filled in by the actual text once we have the apis.

i think that we don't need to have the text selected by the API at the moment, because I think it will simply be a description of what it means to 'vote random' or choose an actual vote. I think this text can be finalized and hard-coded! I don't know what exactly the text is supposed to say exactly haha

**Comment by psc358** [comment]
> > Looks good! Could you also remind me what each of the filler texts is going to be replaced with eventually? Maybe we should add an argument so it can be filled in by the actual text once we have the apis.
> 
> i think that we don't need to have the text selected by the API at the moment, because I think it will simply be a description of what it means to 'vote random' or choose an actual vote. I think this text can be finalized and hard-coded! I don't know what exactly the text is supposed to say exactly haha

Ohh ok sounds good!!

**Review by psc358 — APPROVED** [review]
Looks good!

**Review by thomastai1666 — APPROVED** [review]
Looks good! in the future I'd recommend reusing classnames when possible (as its less work) You have duplicate styles such as main-container-1 and main-container-2 that are identical

**Comment by Golemwardox** [comment]
> Looks good! in the future I'd recommend reusing classnames when possible (as its less work) You have duplicate styles such as main-container-1 and main-container-2 that are identical

Hi! I fixed that. Thank you, I didn't even realize!

**Comment by Jen-Lopez** [comment]
fixed up the merge conflicts so it should be good to merge :)

**Review by Jen-Lopez — APPROVED** [review]
👍🏼

**Pull request merged**
